package com.alexisboiz.boursewatcher.model

import com.google.gson.annotations.SerializedName


data class Gainers (

  @SerializedName("language"                          ) var language                          : String?  = null,
  @SerializedName("region"                            ) var region                            : String?  = null,
  @SerializedName("quoteType"                         ) var quoteType                         : String?  = null,
  @SerializedName("typeDisp"                          ) var typeDisp                          : String?  = null,
  @SerializedName("quoteSourceName"                   ) var quoteSourceName                   : String?  = null,
  @SerializedName("triggerable"                       ) var triggerable                       : Boolean? = null,
  @SerializedName("customPriceAlertConfidence"        ) var customPriceAlertConfidence        : String?  = null,
  @SerializedName("lastCloseTevEbitLtm"               ) var lastCloseTevEbitLtm               : Double?  = null,
  @SerializedName("lastClosePriceToNNWCPerShare"      ) var lastClosePriceToNNWCPerShare      : Double?  = null,
  @SerializedName("currency"                          ) var currency                          : String?  = null,
  @SerializedName("regularMarketChangePercent"        ) var regularMarketChangePercent        : Double?  = null,
  @SerializedName("averageAnalystRating"              ) var averageAnalystRating              : String?  = null,
  @SerializedName("exchange"                          ) var exchange                          : String?  = null,
  @SerializedName("fiftyTwoWeekLow"                   ) var fiftyTwoWeekLow                   : Double?  = null,
  @SerializedName("fiftyTwoWeekHigh"                  ) var fiftyTwoWeekHigh                  : Double?  = null,
  @SerializedName("shortName"                         ) var shortName                         : String?  = null,
  @SerializedName("priceHint"                         ) var priceHint                         : Int?     = null,
  @SerializedName("preMarketChange"                   ) var preMarketChange                   : Double?  = null,
  @SerializedName("preMarketChangePercent"            ) var preMarketChangePercent            : Double?  = null,
  @SerializedName("preMarketTime"                     ) var preMarketTime                     : Int?     = null,
  @SerializedName("preMarketPrice"                    ) var preMarketPrice                    : Double?  = null,
  @SerializedName("regularMarketChange"               ) var regularMarketChange               : Double?  = null,
  @SerializedName("regularMarketTime"                 ) var regularMarketTime                 : Int?     = null,
  @SerializedName("regularMarketPrice"                ) var regularMarketPrice                : Double?  = null,
  @SerializedName("regularMarketDayHigh"              ) var regularMarketDayHigh              : Double?  = null,
  @SerializedName("regularMarketDayRange"             ) var regularMarketDayRange             : String?  = null,
  @SerializedName("regularMarketDayLow"               ) var regularMarketDayLow               : Double?  = null,
  @SerializedName("regularMarketVolume"               ) var regularMarketVolume               : Int?     = null,
  @SerializedName("regularMarketPreviousClose"        ) var regularMarketPreviousClose        : Double?  = null,
  @SerializedName("bid"                               ) var bid                               : Double?     = null,
  @SerializedName("ask"                               ) var ask                               : Double?     = null,
  @SerializedName("bidSize"                           ) var bidSize                           : Int?     = null,
  @SerializedName("askSize"                           ) var askSize                           : Int?     = null,
  @SerializedName("market"                            ) var market                            : String?  = null,
  @SerializedName("messageBoardId"                    ) var messageBoardId                    : String?  = null,
  @SerializedName("fullExchangeName"                  ) var fullExchangeName                  : String?  = null,
  @SerializedName("longName"                          ) var longName                          : String?  = null,
  @SerializedName("financialCurrency"                 ) var financialCurrency                 : String?  = null,
  @SerializedName("regularMarketOpen"                 ) var regularMarketOpen                 : Double?  = null,
  @SerializedName("averageDailyVolume3Month"          ) var averageDailyVolume3Month          : Int?     = null,
  @SerializedName("averageDailyVolume10Day"           ) var averageDailyVolume10Day           : Int?     = null,
  @SerializedName("fiftyTwoWeekLowChange"             ) var fiftyTwoWeekLowChange             : Double?  = null,
  @SerializedName("fiftyTwoWeekLowChangePercent"      ) var fiftyTwoWeekLowChangePercent      : Double?  = null,
  @SerializedName("fiftyTwoWeekRange"                 ) var fiftyTwoWeekRange                 : String?  = null,
  @SerializedName("fiftyTwoWeekHighChange"            ) var fiftyTwoWeekHighChange            : Double?  = null,
  @SerializedName("fiftyTwoWeekHighChangePercent"     ) var fiftyTwoWeekHighChangePercent     : Double?  = null,
  @SerializedName("fiftyTwoWeekChangePercent"         ) var fiftyTwoWeekChangePercent         : Double?  = null,
  @SerializedName("earningsTimestamp"                 ) var earningsTimestamp                 : Int?     = null,
  @SerializedName("earningsTimestampStart"            ) var earningsTimestampStart            : Int?     = null,
  @SerializedName("earningsTimestampEnd"              ) var earningsTimestampEnd              : Int?     = null,
  @SerializedName("marketState"                       ) var marketState                       : String?  = null,
  @SerializedName("epsTrailingTwelveMonths"           ) var epsTrailingTwelveMonths           : Double?  = null,
  @SerializedName("epsForward"                        ) var epsForward                        : Double?  = null,
  @SerializedName("epsCurrentYear"                    ) var epsCurrentYear                    : Double?  = null,
  @SerializedName("priceEpsCurrentYear"               ) var priceEpsCurrentYear               : Double?     = null,
  @SerializedName("bookValue"                         ) var bookValue                         : Double?  = null,
  @SerializedName("fiftyDayAverage"                   ) var fiftyDayAverage                   : Double?  = null,
  @SerializedName("fiftyDayAverageChange"             ) var fiftyDayAverageChange             : Double?  = null,
  @SerializedName("fiftyDayAverageChangePercent"      ) var fiftyDayAverageChangePercent      : Double?  = null,
  @SerializedName("twoHundredDayAverage"              ) var twoHundredDayAverage              : Double?  = null,
  @SerializedName("twoHundredDayAverageChange"        ) var twoHundredDayAverageChange        : Double?  = null,
  @SerializedName("twoHundredDayAverageChangePercent" ) var twoHundredDayAverageChangePercent : Double?  = null,
  @SerializedName("marketCap"                         ) var marketCap                         : Long?     = null,
  @SerializedName("forwardPE"                         ) var forwardPE                         : Double?  = null,
  @SerializedName("priceToBook"                       ) var priceToBook                       : Double?  = null,
  @SerializedName("sourceInterval"                    ) var sourceInterval                    : Int?     = null,
  @SerializedName("exchangeDataDelayedBy"             ) var exchangeDataDelayedBy             : Int?     = null,
  @SerializedName("exchangeTimezoneName"              ) var exchangeTimezoneName              : String?  = null,
  @SerializedName("exchangeTimezoneShortName"         ) var exchangeTimezoneShortName         : String?  = null,
  @SerializedName("gmtOffSetMilliseconds"             ) var gmtOffSetMilliseconds             : Int?     = null,
  @SerializedName("esgPopulated"                      ) var esgPopulated                      : Boolean? = null,
  @SerializedName("tradeable"                         ) var tradeable                         : Boolean? = null,
  @SerializedName("cryptoTradeable"                   ) var cryptoTradeable                   : Boolean? = null,
  @SerializedName("displayName"                       ) var displayName                       : String?  = null,
  @SerializedName("symbol"                            ) var symbol                            : String?  = null,
  @SerializedName("image"                             ) var image                             : String?  = null,
  @SerializedName("open"                              ) var open                              : ArrayList<Double>,
  @SerializedName("close"                             ) var close                             : ArrayList<Double>,
  @SerializedName("volume"                            ) var volume                            : ArrayList<Int>,

)